### ISSUE TITLE
Minecraft Collection Proposal v1

### ISSUE THREAD

**Issue by tozydev** [GrassMC/minecraft-collections#10]
# Minecraft Collections v1

## Definitions

* **Collection**: a list containing items of the same type related to Minecraft such as wikis, tools, software, mods,... It is also considered a category.
* **Item**: an item containing collected information. An item will have the following required components:
  * **Name**: the name of the item, which can be a website name, software name,...
  * **Description**: the description of the category, it will be closely followed by the description, headline,... of the website, software,....
  * **URL**: the link to the item's *home page*

## Requirements

* The largest level will be the collection, the smallest level will be the item.
* There are no subcategories.
* Each collection must have a name and description.
* Each collection must contain items of the same type (same category).
* An item can be a website, a software, a tool,... and it must be related to Minecraft, preferably Minecraft: Java Edition.
* Depending on the collection, each item will have additional fields, but must include: name, description, URL.
* If the item doesn't have a home page, it will be a link to a download or source page.
* Try to collect necessary information, avoid redundant information.
* Try to add download page, source code, and documentation page links.
* Prioritize open source items.

## Data Organization

```yaml
name: Mod Loaders
description: >
  Mod Loaders allow you to load mods that can change Minecraft's game content in some way, such as to make minor 
  adjustments to the game's mechanics or implement entirely new features.
items:
  - name: Forge
    description: Modifications to the Minecraft base files to assist in compatibility between mods.
    url: https://minecraftforge.net/

```
